### ISSUE TITLE
Support Python 3.11 and port app from Qt5 to Qt6

### ISSUE THREAD

**Issue by PekkaSavolainen** [spine-tools/Spine-Toolbox#1896]
Supporting Python 3.11 requires a bit more work than what was required for 3.9 and 3.10. It looks like there is no PySide2 version 5.15 for Python 3.11 and there never will be. The Qt people have moved on from Qt5 to Qt6 and the Python binding library for Qt6 is called PySide6. So, to support Python 3.11, we 'just' need to port our PySide2 app to PySide6. I already made a very quick port and got Spine Toolbox running on Python 3.11 and PySide6. However, this is a rough first version and I'm sure there are lots of little things that need fixing in Qt6.

**Comment by jkiviluo** [comment]
Sounds very nice though.

**Comment by jkiviluo** [comment]
I got it working in 3.11. Scenario choice buttons are not working in the DB resource filters.

**Comment by PekkaSavolainen** [comment]
> I got it working in 3.11. Scenario choice buttons are not working in the DB resource filters.

Thanks. I missed the check boxes in Link Properties for some reason but they should be fixed now.

**Comment by jkiviluo** [comment]
That seems to happen when running a merger tool with a scenario(s) selected. (I should run it without any scenarios, but those scenarios are automatically added to the selection...)

**Comment by jkiviluo** [comment]
BTW, I don't think this is PySide 6 related - the other person that saw the same error is not using PySide6 branch. Probably some other recent change.

**Comment by PekkaSavolainen** [comment]
> AttributeError: 'PySide6.QtGui.QTextCursor' object has no attribute 'NextBlock'. Did you mean: 'insertBlock'?

Yes, the AttributeError is pyside6 related and it's now fixed.

**Comment by PekkaSavolainen** [comment]
Note that pyside6 v6.4.2 is broken and it's been disallowed in our setup.cfg files. The version is incompatible with pywin32. This [bug has already been fixed](https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-2189?filter=allopenissues) so the upcoming pyside6 releases should work again.

**Comment by jkiviluo** [comment]
I'm getting quite a lot of this. Not sure if it's qt6 related.

```
RuntimeError: can't associate parent <spinetoolbox.spine_db_editor.mvcmodels.compound_parameter_models.CompoundObjectParameterDefinitionModel(0x1478e113730) at 0x000001478601C3C0> to listener <spinetoolbox.spine_db_editor.widgets.spine_db_editor.SpineDBEditor(0x147f6ae5980, name="MainWindow") at 0x000001478D424640> - not listening on DB map <spinedb_api.diff_db_mapping.DiffDatabaseMapping object at 0x000001478D130E20>
Traceback (most recent call last):
  File "C:\data\SpineToolbox-qt6\spinetoolbox\spine_db_editor\mvcmodels\compound_parameter_models.py", line 70, in canFetchMore
    return any(self.db_mngr.can_fetch_more(db_map, self, listener=self._parent) for db_map in self.db_maps)
  File "C:\data\SpineToolbox-qt6\spinetoolbox\spine_db_editor\mvcmodels\compound_parameter_models.py", line 70, in <genexpr>
    return any(self.db_mngr.can_fetch_more(db_map, self, listener=self._parent) for db_map in self.db_maps)
  File "C:\data\SpineToolbox-qt6\spinetoolbox\spine_db_manager.py", line 248, in can_fetch_more
    raise RuntimeError(
```

**Comment by manuelma** [comment]
No, that's not Qt-related.

**Comment by manuelma** [comment]
That's something that I fixed in the async branch - but if you want to fix it in master you just need to remove the raise, it's not very important.

**Comment by PekkaSavolainen** [comment]
The PySide6 and Python 3.11 branches have been merged to master. Please do `pip install -r requirements.txt --upgrade`. Supported Pythons are now 3.8-3.11 and supported PySide6 version is 6.4.0 or greater.
